import assert from 'node:assert/strict';
import {readFileSync, mkdirSync, writeFileSync} from 'node:fs';
import {chromium} from '../../../node_modules/@playwright/test/index.mjs';
import {startPreview} from './preview.mjs';
const fixture = await startPreview(9833);
const evidence = process.env.PRACTICE_EVIDENCE || '/tmp/kk-practice-evidence';
mkdirSync(evidence, {recursive: true});
const browser = await chromium.launch({headless: true, ...(process.env.PRACTICE_CHROME ? {executablePath: process.env.PRACTICE_CHROME} : {})});
const report = {version: fixture.ids.version, checks: [], previewMilliseconds: []};
try {
  const context = await browser.newContext({viewport: {width: 1280, height: 900}, reducedMotion: 'reduce'});
  const page = await context.newPage();
  const requests = [], errors = [];
  page.on('request', request => requests.push(request.url() + (request.postData() || '')));
  page.on('console', message => {if (message.type() === 'error') errors.push(message.text());});
  page.on('pageerror', error => errors.push(error.message));
  const practice = fixture.url + '/?page_id=' + fixture.ids.practice;
  const journey = await context.newPage();
  await journey.route('https://www.googletagmanager.com/**', route=>route.fulfill({body:'',contentType:'application/javascript'}));
  await journey.goto(fixture.url+'/?page_id='+fixture.ids.control);
  await journey.getByRole('link',{name:'Prepare my brief',exact:true}).click();
  await journey.waitForFunction(()=>document.querySelector('#kk-practice-0')?.disabled===false);
  assert.ok(await journey.locator('#kk-practice-0').isEnabled());
  await journey.close(); report.checks.push('source to exercise navigation');
  const response=await page.goto(practice, {waitUntil: 'networkidle'});
  const csp=response.headers()['content-security-policy'];
  assert.ok(csp.includes("connect-src 'none'") && csp.includes("form-action 'none'"));
  const nonce=await page.locator('script[src*="kk-practice"]').evaluate(el=>el.nonce);
  assert.ok(nonce && csp.includes("'nonce-"+nonce+"'"));
  const colors = await page.locator('.kk-practice').evaluate(el => {const c=getComputedStyle(el);return {foreground:c.color,background:c.backgroundColor};});
  const luminance = rgb => {const c=rgb.match(/\d+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4;});return c[0]*.2126+c[1]*.7152+c[2]*.0722;};
  const lum=[luminance(colors.foreground),luminance(colors.background)].sort((a,b)=>a-b); report.contrast=(lum[1]+.05)/(lum[0]+.05); assert.ok(report.contrast>=4.5, JSON.stringify(colors));
  assert.ok((await page.locator('.kk-practice-field textarea').first().isEnabled()));
  await page.getByRole('button', {name: 'Preview my brief', exact: true}).click();
  assert.equal((await page.locator('#kk-practice-result').inputValue()).split('Not provided.').length - 1, 6);
  await page.screenshot({path: evidence + '/empty.png', fullPage: true});
  const canary = 'KK_CANARY_982_<img src="https://invalid.example/steal" onerror="window.pwned=1">';
  for (let index = 0; index < 6; index++) await page.locator('#kk-practice-' + index).fill(canary + '\nAnswer ' + index);
  const timing = await page.evaluate(() => {const start = performance.now(); document.querySelector('[data-action="preview"]').click(); return performance.now() - start;});
  report.previewMilliseconds.push(timing); assert.ok(timing < 100);
  assert.equal(await page.evaluate(() => window.pwned), undefined);
  let brief = await page.locator('#kk-practice-result').inputValue();
  assert.ok(brief.startsWith('# My work brief\n\n## 1. Objective\n\n'));
  await page.locator('#kk-practice-result').fill(brief + '\nManual revision');
  await page.getByRole('button', {name: 'Back to answers'}).click();
  await page.getByRole('button', {name: 'Preview my brief', exact: true}).click();
  assert.ok((await page.locator('#kk-practice-result').inputValue()).endsWith('Manual revision'));
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', {value: {writeText: async () => {throw new Error('denied');}}, configurable: true}));
  await page.getByRole('button', {name: 'Copy brief', exact: true}).click();
  assert.ok((await page.locator('.kk-practice-status').innerText()).includes('Copy did not work'));
  assert.equal(await page.locator('#kk-practice-result').evaluate(el => el.selectionEnd - el.selectionStart), (await page.locator('#kk-practice-result').inputValue()).length);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Download Markdown'}).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(), 'my-work-brief.md');
  assert.equal(readFileSync(await download.path(), 'utf8'), await page.locator('#kk-practice-result').inputValue());
  await page.evaluate(() => {window.print = () => {window.printedBrief = document.querySelector('.kk-practice-print').textContent;};});
  await page.getByRole('button', {name: 'Print brief', exact: true}).click();
  assert.equal(await page.evaluate(() => window.printedBrief), await page.locator('#kk-practice-result').inputValue());
  await page.evaluate(()=>document.querySelector('.kk-practice').classList.add('kk-practice-printing'));
  await page.emulateMedia({media:'print'});
  assert.ok(await page.locator('.kk-practice-print').isVisible());
  assert.ok(!(await page.locator('img[src="/north-house.jpg"]').isVisible()));
  assert.ok(!(await page.locator('.aurora-header').isVisible()));
  assert.ok(!(await page.locator('.aurora-footer-2026').isVisible()));
  await page.pdf({path:evidence+'/brief-print.pdf',format:'A4'});
  await page.emulateMedia({media:'screen'});
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.evaluate(()=>document.querySelector('.kk-practice').classList.remove('kk-practice-printing'));
  report.checks.push('print media and PDF excludes page photo/header');
  await page.screenshot({path: evidence + '/complete-desktop.png', fullPage: true});
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({width, height: 900});
    assert.ok(await page.locator('.kk-practice').evaluate(el => el.scrollWidth <= el.clientWidth + 1), 'Practice overflow at ' + width);
    await page.screenshot({path: evidence + '/width-' + width + '.png', fullPage: true});
    const nav=page.locator('.aurora-primary-nav a').last(); await nav.focus();
    assert.ok(await nav.evaluate(el=>el===document.activeElement && getComputedStyle(el).display!=='none'));
  }
  await page.setViewportSize({width: 1280, height: 900});
  await page.evaluate(() => {document.documentElement.style.zoom='2';});
  assert.ok(await page.locator('.kk-practice').evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  await page.screenshot({path:evidence+'/zoom-200.png',fullPage:true});
  await page.evaluate(() => {document.documentElement.style.zoom='';});
  report.checks.push('computed normal-text contrast', '200% CSS zoom reflow');
  await page.locator('#kk-practice-0').fill('x'.repeat(8001));
  assert.ok(await page.getByRole('button', {name: 'Preview my brief', exact: true}).isDisabled());
  assert.equal((await page.locator('#kk-practice-0').inputValue()).length, 8001);
  await page.screenshot({path: evidence + '/over-limit.png', fullPage: true});
  for (let index = 0; index < 6; index++) await page.locator('#kk-practice-' + index).fill('');
  await page.locator('#kk-practice-0').fill('😀'.repeat(8000));
  assert.ok(await page.getByRole('button', {name: 'Preview my brief', exact: true}).isEnabled());
  assert.ok(requests.every(value => !value.includes('googletagmanager.com') && !value.includes('google-analytics.com')));
  assert.ok(requests.every(value => !value.includes('KK_CANARY') && !value.includes('invalid.example')));
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
  assert.deepEqual(await context.cookies(), []);
  assert.equal(await page.evaluate(async () => (await indexedDB.databases()).length), 0);
  assert.deepEqual(errors, []);
  const probe=await context.newPage(); const probeErrors=[]; probe.on('console',m=>{if(m.type()==='error')probeErrors.push(m.text());});
  await probe.goto(practice+'&raw_probe=1');
  assert.equal(await probe.evaluate(()=>window.rawProbeExecuted),undefined);
  assert.ok(probeErrors.some(text=>text.includes('Content Security Policy')));
  await probe.close(); report.checks.push('CSP nonce/header', 'raw script denied (expected isolated CSP error)');
  report.checks.push('empty draft', 'six fields', 'literal adversarial input', 'editable output preserved', 'copy failure', 'exact Markdown bytes', 'print text', 'four widths', '8000 Unicode characters', 'privacy network/storage/cookies', 'clean console');
  await page.goto(practice);
  await page.getByRole('button', {name: 'Prepare my brief', exact: true}).focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#kk-practice-0').evaluate(el => el === document.activeElement), true);
  for (let index = 0; index < 6; index++) {await page.keyboard.type('Keyboard answer'); await page.keyboard.press('Tab');}
  await page.keyboard.press('Enter');
  assert.ok(await page.locator('.kk-practice-output').isVisible());
  report.checks.push('keyboard-only artifact');
  const nojs = await browser.newContext({javaScriptEnabled: false});
  const fallbackPage = await nojs.newPage(); await fallbackPage.goto(practice);
  assert.ok(await fallbackPage.locator('.kk-practice-nojs').isVisible());
  assert.equal(await fallbackPage.locator('.kk-practice-field').count(), 6);
  await fallbackPage.screenshot({path: evidence + '/no-js.png', fullPage: true});
  await nojs.close();
  const failedImage = await context.newPage(); await failedImage.route('**/north-house.jpg', route => route.abort());
  await failedImage.goto(practice); assert.ok(await failedImage.locator('#kk-practice-0').isEnabled());
  await failedImage.screenshot({path: evidence + '/missing-image.png', fullPage: true}); await failedImage.close();
  const control = await context.newPage(); let gtag = false;
  await control.route('https://www.googletagmanager.com/**', route => {gtag = true; return route.fulfill({body: '', contentType: 'application/javascript'});});
  await control.goto(fixture.url + '/?page_id=' + fixture.ids.control);
  assert.equal(await control.locator('script[src*="kk-practice"]').count(), 0);
  await control.keyboard.press('Tab'); await control.waitForTimeout(1500); assert.ok(gtag, 'Actual #706 loader must fire on control');
  report.checks.push('no-JS worksheet', 'failed image', 'route-only assets', 'positive #706 control');
  await page.goto(fixture.url + '/?page_id=' + fixture.ids.nested);
  assert.equal(await page.locator('.kk-practice-field textarea').count(),0);
  assert.equal(await page.locator('.kk-practice-worksheet h3').count(),6);
  report.checks.push('nested placement fails closed');
  await fixture.server.playground.run({code: '<?php require "/wordpress/wp-load.php"; wp_set_password("practice-fixture-password", 1);'});
  const editor = await context.newPage();
  await editor.goto(fixture.url + '/wp-login.php');
  await editor.locator('#user_login').fill('admin');
  await editor.locator('#user_pass').fill('practice-fixture-password');
  await editor.locator('#wp-submit').click();
  await editor.goto(fixture.url + '/wp-admin/post.php?post=' + fixture.ids.practice + '&action=edit');
  await editor.waitForFunction(() => window.wp?.data?.select('core/block-editor')?.getBlocks().length > 0);
  const editorState = await editor.evaluate(() => {
    const blocks=wp.data.select('core/block-editor').getBlocks();
    const block=blocks.find(b=>b.name==='kk/context-brief');
    return {registered:!!wp.blocks.getBlockType('kk/context-brief'),valid:block?.isValid,attributes:block?.attributes};
  });
  assert.equal(editorState.registered,true); assert.equal(editorState.valid,true); assert.deepEqual(editorState.attributes,{});
  await editor.evaluate(async () => {await wp.data.dispatch('core/editor').savePost();});
  await editor.reload();
  await editor.waitForFunction(() => window.wp?.data?.select('core/block-editor')?.getBlocks().some(b=>b.name==='kk/context-brief'));
  assert.equal(await editor.evaluate(() => wp.data.select('core/block-editor').getBlocks().find(b=>b.name==='kk/context-brief').isValid),true);
  report.checks.push('real editor registered/save/reopen valid block');
  await editor.close();
  const rollback = await fixture.server.playground.run({code: '<?php require "/wordpress/wp-load.php"; require_once ABSPATH . "wp-admin/includes/plugin.php"; deactivate_plugins("kk-practice/kk-practice.php"); echo "deactivated";'});
  assert.equal(rollback.text, 'deactivated');
  await fallbackPage.close();
  await page.goto(practice); assert.equal(await page.locator('.kk-practice-worksheet h3').count(), 6);
  assert.equal(await page.locator('.kk-practice-field').count(), 0);
  report.checks.push('actual plugin deactivation with editor.save fallback');
  const logs = await fixture.server.playground.run({code: '<?php $p="/wordpress/wp-content/debug.log"; echo file_exists($p) ? file_get_contents($p) : "";'});
  assert.ok(!logs.text.includes('KK_CANARY'));
  report.checks.push('application log canary absent');
  writeFileSync(evidence + '/report.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); await fixture.close(); }
